### ISSUE TITLE
All messages are not clearly displayed while running .configure file

### ISSUE THREAD

**Issue by guits** [enovance/edeploy#202]
Hello,

when running command in the .configure file, there is something that redirect all message to `/dev/null` or something like that.

i recently had to deploy a node, i've got a problem with this command : 

```
run('lvcreate rootfs -n slash -l 100%FREE')
```
which was resulting to :

```
"WARNING: ext4 signature detected on /dev/rootfs/slash at offset 1080. Wipe it? [y/n]"
```
so eDeploy stopped the process because waiting for an answer.

The problem is as the message was not clearly displayed, it was a little bit more difficult to make some debug to understand what was going wrong.

Maybe we should have a way to be able to display these messages ?

**Comment by ErwanAliasr1** [comment]
Perfectly true, that was hard to debug. Looking at it.

**Comment by ErwanAliasr1** [comment]
That is solving your issue.
