### ISSUE TITLE
initrd failure if system-product-name comes with a comas

### ISSUE THREAD

**Issue by goneri** [enovance/edeploy#203]
I hope the picture is enough. Basically, cur truncat the file name and so failed to push the file.

![pour_erwan](https://cloud.githubusercontent.com/assets/49379/5839116/5790e7bc-a18c-11e4-93dd-e9f14bf59d96.png)

**Comment by goneri** [comment]
`dmidecode -s system-product-name` returns `Standard PC (i440FX + PIIX, 1996)`

**Comment by ErwanAliasr1** [comment]
@goneri Can you confirm the bug is closed with this fix ?
