### ISSUE TITLE
blade nodes with the same serial (but different uuid) overwrite each others files

### ISSUE THREAD

**Issue by gerhardqux** [enovance/edeploy#206]
We have a chassis with four servers in it. 

The hw file gets its name based on this format:
  <dmi_product_name>-<dmi_product_version>-{dmi_serial_num|mac_address}

If dmi_serial_num is set, mac_address is not used. But since all four servers report the same serial, the .hw file gets overwritten.

Should the serial actually be used for this filename?

**Comment by ErwanAliasr1** [comment]
I had the case in past with some stupid boards. I've been implementing that workaround: https://github.com/enovance/hardware/blob/master/hardware/detect.py#L453

Maybe, you can just add your serial in this quirk list and make a PR for it.

**Comment by ErwanAliasr1** [comment]
Solved by https://github.com/enovance/hardware/commit/337c06ce39d375a212f8cbe716d7b45a85ebfa12
