### ISSUE TITLE
System product name with a slash in it prevents the logfile from being uploaded.

### ISSUE THREAD

**Issue by gerhardqux** [enovance/edeploy#207]
We have a system with this product name:

('system', 'product', 'name', 'X9DRD-iF/LF (To be filled by O.E.M.)'),

upload.py bails out because the directory X9DRD-iF doesn't exist. 

This helps in init.common:
-    log_file="${vendor}-${product}-${serial}.log.gz"
+    log_file=$(echo "${vendor}-${product}-${serial}.log.gz" | sed 's/[^A-Za-z0-9\-_.]/_/g')

I hope to create a pull request shortly.

**Comment by ErwanAliasr1** [comment]
That is fixed by https://github.com/enovance/edeploy/commit/9706d3adeab4af156698d166ee73c1a3c2888e76 isn't it ?

**Comment by ErwanAliasr1** [comment]
I'm closing this one since the current code does solve this issue.
