### ISSUE TITLE
Upgrade fails if SElinux enforced 

### ISSUE THREAD

**Issue by EmilienM** [enovance/edeploy#211]
On RHEL 7, with SElinux enforced, edeploy upgrade does not work with -X rsync option. 

http://paste.openstack.org/show/r8v1FXth25JO2PqoIYrz/

**Comment by EmilienM** [comment]
The bug is not only for metadatas, but also for role files.

**Comment by EmilienM** [comment]
I think before the actual rsync, we should create a SELinux boolean to allow rsync access all the files (except security files):

 setsebool -P rsync_full_access 1

**Comment by EmilienM** [comment]
Same result with:
setsebool -P rsync_full_access 1
setsebool -P rsync_client 1

type=USER_CMD msg=audit(1424028002.845:17156): pid=16581 uid=998 auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 msg='cwd="/" cmd=6F73636865636B732D636865636B5F616D7170206E6F76612D636F6E736F6C6561757468 terminal=? res=failed'

**Comment by TristanCacqueray** [comment]
However, giving rsync the permission to change labels does not sounds like a great idea...
Maybe we better look for giving the edeploy process the proper role like sysadm_r

**Comment by EmilienM** [comment]
@TristanCacqueray with/without permissions, the upgrade fails so for now I don't give the permissions.
The weird thing is in audit.log, where no rule is suggested. I'm still investigating.

**Comment by EmilienM** [comment]
It's fixed by https://github.com/enovance/edeploy-roles/commit/af430c26f8971baefed5e7177b961d60ab3444cc
