### ISSUE TITLE
HP Gen8 servers hang when using "localboot 0"

### ISSUE THREAD

**Issue by AlexandreNo** [enovance/edeploy#224]
Hi,

Due to a BIOS bug on some HP servers (mostly Gen8) they hang when PXE boot try to do a "localboot 0".
Instead we need boot directly from the HD:
label localboot
     com32 chain.c32
     append hdX (where X is your booting harddrive).

The chain.c32 file must be available from the tftp server for the server to download it.

**Comment by ErwanAliasr1** [comment]
The previous commit will ease what you suggest here. We should have done that before. Thanks.
