### ISSUE TITLE
cmdb not expand without error

### ISSUE THREAD

**Issue by gaelL** [enovance/edeploy#240]
Hi,

Some people have this issue : 

  * A `cmdb` file `with generate`function
  * All looks fine.
  * `KeyError` in `.configure` for a variable using range behavior.
  * No error for statics vars.

In all case I have seen, it was linked to https://github.com/enovance/hardware/blob/master/hardware/cmdb.py#L47

when you call `upload.py`, `hardware` module try to create a `.orig` file. For example `/etc/edeploy/foo.cmdb.orig`.
If you have not the write permission on edeploy directory, this action fail without errors in edeploy.

The result is edeploy continue and launch the configure script without expanded variables.

I think we need to have log or a message for this issue in edeploy.

Gaël L

**Comment by fredericlepied** [comment]
Fixed in https://github.com/enovance/hardware/commit/840497127fe69bd944a6e7c5dc5bec532f7fa296
